global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

rule_files:
  - "recording-rules.yml"

scrape_configs:
  - job_name: master-data-service
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["master-data-service:8000"]
  - job_name: query-service
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["query-service:8000"]
