#
# Copyright 2023 Jaroslav Chmurny
#
# This file is part of City Navigator.
#
# City Navigator is free software developed for educational and experimental
# purposes. It is licensed under the Apache License, Version 2.0 # (the
# "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

services:
  postgres-db:
    image: jardo72/city-navigator-postgres:latest
    environment:
      - POSTGRES_USER=master_data_svc_tu
      - POSTGRES_PASSWORD=T0pS3cr3tP8ssw0rd
      - POSTGRES_DB=city_navigator
    expose:
      - 5432
    networks:
      - service-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U master_data_svc_tu -d city_navigator"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s

  data-importer:
    image: jardo72/city-navigator-data-importer:latest
    command: ["city-plan.json", "postgresql://master_data_svc_tu:T0pS3cr3tP8ssw0rd@postgres-db:5432/city_navigator"]
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - service-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 5s

  redis-pubsub:
    image: redis:7-alpine
    expose:
      - 6379
    networks:
      - service-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s

  master-data-service:
    image: jardo72/city-navigator-master-data-service:latest
    depends_on:
      redis-pubsub:
        condition: service_started
      data-importer:
        condition: service_completed_successfully
      prometheus-http-discovery:
        condition: service_started
    environment:
      # if API doc is enabled, metrics scraping does not work
      - API_DOC_ENABLED=no
      - ROOT_PATH=/city-navigator/api/master-data
      - ACCESS_LOG=/access-logs/master-data-service-access.log
      - DATABASE_URL=postgresql://master_data_svc_tu:T0pS3cr3tP8ssw0rd@postgres-db:5432/city_navigator
      - REDIS_HOST=redis-pubsub
      - REDIS_PORT=6379
      - PROMETHEUS_DISCOVERY_BASE_URL=http://prometheus-http-discovery:8000
    expose:
      - 8000
    networks:
      - service-network
    volumes:
      - type: bind
        source: ./access-logs
        target: /access-logs
        read_only: false
      - type: bind
        source: ./app-logs
        target: /app-logs
        read_only: false
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 250M
        limits:
          cpus: '0.5'
          memory: 750M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s

  query-service:
    image: jardo72/city-navigator-query-service:latest
    depends_on:
      redis-pubsub:
        condition: service_started
      master-data-service:
        condition: service_started
      prometheus-http-discovery:
        condition: service_started
    environment:
      # if API doc is enabled, metrics scraping does not work
      - API_DOC_ENABLED=no
      - ROOT_PATH=/city-navigator/api/query
      - ACCESS_LOG=/access-logs/query-service-access.log
      - MASTER_DATA_SERVICE_BASE_URL=http://master-data-service:8000
      - REDIS_HOST=redis-pubsub
      - REDIS_PORT=6379
      - PROMETHEUS_DISCOVERY_BASE_URL=http://prometheus-http-discovery:8000
    expose:
      - 8000
    networks:
      - service-network
    volumes:
      - type: bind
        source: ./access-logs
        target: /access-logs
        read_only: false
      - type: bind
        source: ./app-logs
        target: /app-logs
        read_only: false
    deploy:
      mode: replicated
      replicas: 2
      resources:
        reservations:
          cpus: '1.5'
          memory: 1G
        limits:
          cpus: '3.5'
          memory: 3G
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s

  nginx-http-router:
    image: nginx:1.27-alpine
    depends_on:
      master-data-service:
        condition: service_started
      query-service:
        condition: service_started
    expose:
      - 80
    networks:
      - service-network
    volumes:
      - type: bind
        source: ./nginx
        target: /etc/nginx
        read_only: true
    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s

  prometheus-server:
    image: prom/prometheus
    depends_on:
      master-data-service:
        condition: service_started
      query-service:
        condition: service_started
    networks:
      - service-network
      - monitoring-network
    volumes:
      - type: bind
        source: ./prometheus
        target: /etc/prometheus/
        read_only: true
    ports:
      - 9090:9090
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s

  prometheus-http-discovery:
    image: jardo72/city-navigator-http-service-discovery:latest
    environment:
      - ACCESS_LOG=/access-logs/http-service-discovery-access.log
    expose:
      - 8000
    networks:
      - service-network
      - monitoring-network
    volumes:
      - type: bind
        source: ./access-logs
        target: /access-logs
        read_only: false
      - type: bind
        source: ./app-logs
        target: /app-logs
        read_only: false
    ports:
      - 9099:8000
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s

  grafana:
    image: grafana/grafana
    depends_on:
      prometheus-server:
        condition: service_started
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=GrafanaSecret#37
    networks:
      - monitoring-network
    volumes:
      - type: bind
        source: ./grafana/datasources
        target: /etc/grafana/provisioning/datasources
        read_only: true
      - type: bind
        source: ./grafana/dashboards
        target: /etc/grafana/provisioning/dashboards
        read_only: true
    ports:
      - 3000:3000

  loki:
    image: grafana/loki
    profiles:
      - logging
    networks:
      - monitoring-network
    volumes:
      - type: bind
        source: ./loki
        target: /etc/loki
        read_only: true
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - 3100:3100
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s

  promtail:
    image: grafana/promtail
    profiles:
      - logging
    depends_on:
      loki:
        condition: service_started
    networks:
      - monitoring-network
    volumes:
      - type: bind
        source: ./promtail
        target: /etc/promtail
        read_only: true
      - type: bind
        source: ./app-logs
        target: /app-logs
        read_only: true
    command: -config.file=/etc/promtail/promtail-config.yml
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s

networks:
  service-network:
    driver: bridge
  monitoring-network:
    driver: bridge
