CREATE TABLE MEANS_OF_TRANSPORT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    IDENTIFIER VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE NODES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE EDGES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    START_NODE_ID INTEGER NOT NULL,
    END_NODE_ID INTEGER NOT NULL,
    MEANS_OF_TRANSPORT_ID INTEGER NOT NULL,
    DISTANCE_MIN INTEGER NOT NULL,
    CONSTRAINT MEANS_OF_TRANSPORT_FK FOREIGN KEY (MEANS_OF_TRANSPORT_ID) REFERENCES MEANS_OF_TRANSPORT(ID),
    CHECK (DISTANCE_MIN > 0),
    CONSTRAINT START_NODE_FK FOREIGN KEY (START_NODE_ID) REFERENCES NODES(ID),
    CONSTRAINT END_NODE_FK FOREIGN KEY (END_NODE_ID) REFERENCES NODES(ID)
);

CREATE TABLE LINE_ITINERARY_ENTRIES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EDGE_ID INTEGER NOT NULL,
    NEXT_ENTRY_ID INTEGER,
    CONSTRAINT EDGE_FK FOREIGN KEY (EDGE_ID) REFERENCES EDGES(ID)
    CONSTRAINT NEXT_ENTRY_FK FOREIGN KEY (NEXT_ENTRY_ID) REFERENCES LINE_ITINERARY_ENTRIES(ID)
);

CREATE TABLE LINES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MEANS_OF_TRANSPORT_ID INTEGER NOT NULL,
    LABEL VARCHAR(5) NOT NULL UNIQUE,
    ITINERARY_START_DIRECTION_ONE_ID INTEGER NOT NULL,
    ITINERARY_START_DIRECTION_TWO_ID INTEGER NOT NULL,
    CONSTRAINT MEANS_OF_TRANSPORT_FK FOREIGN KEY (MEANS_OF_TRANSPORT_ID) REFERENCES MEANS_OF_TRANSPORT(ID),
    CONSTRAINT ITINERARY_START_DIRECTION_ONE_FK FOREIGN KEY (ITINERARY_START_DIRECTION_ONE_ID) REFERENCES LINE_ITINERARY_ENTRIES(ID),
    CONSTRAINT ITINERARY_START_DIRECTION_TWO_FK FOREIGN KEY (ITINERARY_START_DIRECTION_TWO_ID) REFERENCES LINE_ITINERARY_ENTRIES(ID)
);
