INSERT INTO MEANS_OF_TRANSPORT (IDENTIFIER) VALUES('S-Bahn');
INSERT INTO MEANS_OF_TRANSPORT (IDENTIFIER) VALUES('U-Bahn');
INSERT INTO MEANS_OF_TRANSPORT (IDENTIFIER) VALUES('Bus');
INSERT INTO MEANS_OF_TRANSPORT (IDENTIFIER) VALUES('Tram');

INSERT INTO NODES (NAME) VALUES('Floridsdorf');
INSERT INTO NODES (NAME) VALUES('Kagran');
INSERT INTO NODES (NAME) VALUES('Simmering');
INSERT INTO NODES (NAME) VALUES('Enkplatz');
INSERT INTO NODES (NAME) VALUES('Zippererstrasse');
INSERT INTO NODES (NAME) VALUES('Ottakring');

INSERT INTO LINES (LABEL, MEANS_OF_TRANSPORT_ID, TERMINAL_STOP_ONE_ID, TERMINAL_STOP_TWO_ID)
VALUES (
    "U3",
    (SELECT ID FROM MEANS_OF_TRANSPORT WHERE IDENTIFIER = 'U-Bahn'),
    (SELECT ID FROM NODES WHERE NAME = 'Simmering'),
    (SELECT ID FROM NODES WHERE NAME = 'Ottakring')
);

INSERT INTO EDGES (START_NODE_ID, END_NODE_ID, LINE_ID, DISTANCE_MIN)
VALUES (
    (SELECT ID FROM NODES WHERE NAME = 'Simmering'),
    (SELECT ID FROM NODES WHERE NAME = 'Enkplatz'),
    (SELECT ID FROM LINES WHERE LABEL = 'U3'),
    2
);

INSERT INTO EDGES (START_NODE_ID, END_NODE_ID, LINE_ID, DISTANCE_MIN)
VALUES (
    (SELECT ID FROM NODES WHERE NAME = 'Enkplatz'),
    (SELECT ID FROM NODES WHERE NAME = 'Zippererstrasse'),
    (SELECT ID FROM LINES WHERE LABEL = 'U3'),
    1
);

INSERT INTO EDGES (START_NODE_ID, END_NODE_ID, LINE_ID, DISTANCE_MIN)
VALUES (
    (SELECT ID FROM NODES WHERE NAME = 'Zippererstrasse'),
    (SELECT ID FROM NODES WHERE NAME = 'Enkplatz'),
    (SELECT ID FROM LINES WHERE LABEL = 'U3'),
    1
);

INSERT INTO EDGES (START_NODE_ID, END_NODE_ID, LINE_ID, DISTANCE_MIN)
VALUES (
    (SELECT ID FROM NODES WHERE NAME = 'Enkplatz'),
    (SELECT ID FROM NODES WHERE NAME = 'Simmering'),
    (SELECT ID FROM LINES WHERE LABEL = 'U3'),
    2
);
