INSERT INTO MEANS_OF_TRANSPORT (IDENTIFIER) VALUES('S-Bahn');
INSERT INTO MEANS_OF_TRANSPORT (IDENTIFIER) VALUES('U-Bahn');
INSERT INTO MEANS_OF_TRANSPORT (IDENTIFIER) VALUES('Bus');
INSERT INTO MEANS_OF_TRANSPORT (IDENTIFIER) VALUES('Tram');

INSERT INTO NODES (NAME) VALUES('Floridsdorf');
INSERT INTO NODES (NAME) VALUES('Kagran');
INSERT INTO NODES (NAME) VALUES('Simmering');
INSERT INTO NODES (NAME) VALUES('Enkplatz');
INSERT INTO NODES (NAME) VALUES('Zippererstrasse');

INSERT INTO EDGES (START_NODE_ID, END_NODE_ID, DISTANCE_MIN)
VALUES (
    (SELECT ID FROM NODES WHERE NAME = 'Simmering'),
    (SELECT ID FROM NODES WHERE NAME = 'Enkplatz'),
    2
);

INSERT INTO EDGES (START_NODE_ID, END_NODE_ID, DISTANCE_MIN)
VALUES (
    (SELECT ID FROM NODES WHERE NAME = 'Enkplatz'),
    (SELECT ID FROM NODES WHERE NAME = 'Zippererstrasse'),
    1
);

INSERT INTO EDGES (START_NODE_ID, END_NODE_ID, DISTANCE_MIN)
VALUES (
    (SELECT ID FROM NODES WHERE NAME = 'Zippererstrasse'),
    (SELECT ID FROM NODES WHERE NAME = 'Enkplatz'),
    1
);

INSERT INTO EDGES (START_NODE_ID, END_NODE_ID, DISTANCE_MIN)
VALUES (
    (SELECT ID FROM NODES WHERE NAME = 'Enkplatz'),
    (SELECT ID FROM NODES WHERE NAME = 'Simmering'),
    2
);
