CREATE TABLE NODES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE EDGES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    START_NODE_ID INTEGER NOT NULL,
    END_NODE_ID INTEGER NOT NULL,
    DISTANCE_MIN INTEGER NOT NULL,
    CHECK (DISTANCE_MIN > 0),
    FOREIGN KEY (START_NODE_ID) REFERENCES NODES(ID),
    FOREIGN KEY (END_NODE_ID) REFERENCES NODES(ID)
);
