CREATE TABLE MEANS_OF_TRANSPORT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    IDENTIFIER VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE NODES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE EDGES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    START_NODE_ID INTEGER NOT NULL,
    END_NODE_ID INTEGER NOT NULL,
    MEANS_OF_TRANSPORT_ID INTEGER NOT NULL,
    DISTANCE_MIN INTEGER NOT NULL,
    CONSTRAINT MEANS_OF_TRANSPORT_FK FOREIGN KEY (MEANS_OF_TRANSPORT_ID) REFERENCES MEANS_OF_TRANSPORT(ID),
    CHECK (DISTANCE_MIN > 0),
    CONSTRAINT START_NODE_FK FOREIGN KEY (START_NODE_ID) REFERENCES NODES(ID),
    CONSTRAINT END_NODE_FK FOREIGN KEY (END_NODE_ID) REFERENCES NODES(ID)
);

CREATE TABLE LINES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MEANS_OF_TRANSPORT_ID INTEGER NOT NULL,
    LABEL VARCHAR(5) NOT NULL UNIQUE,
    TERMINAL_STOP_ONE_ID INTEGER NOT NULL,
    TERMINAL_STOP_TWO_ID INTEGER NOT NULL,
    CONSTRAINT TERMINAL_STOPS_CK CHECK (TERMINAL_STOP_ONE_ID <> TERMINAL_STOP_TWO_ID),
    CONSTRAINT MEANS_OF_TRANSPORT_FK FOREIGN KEY (MEANS_OF_TRANSPORT_ID) REFERENCES MEANS_OF_TRANSPORT(ID),
    CONSTRAINT TERMINAL_STOP_ONE_FK FOREIGN KEY (TERMINAL_STOP_ONE_ID) REFERENCES NODES(ID),
    CONSTRAINT TERMINAL_STOP_TWO_FK FOREIGN KEY (TERMINAL_STOP_TWO_ID) REFERENCES NODES(ID)
);
