apiVersion: v1
kind: Service
metadata:
  name: master-data-svc-service
  labels:
    application: city-navigator
    component: master-data-service
    environment: sandbox
spec:
  type: ClusterIP
  selector:
    application: city-navigator
    component: master-data-service
    environment: sandbox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
