#
# Copyright 2023 Jaroslav Chmurny
#
# This file is part of City Navigator.
#
# City Navigator is free software developed for educational and experimental
# purposes. It is licensed under the Apache License, Version 2.0 # (the
# "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: city-navigator
  labels:
    application: city-navigator
    component: prometheus-server
    environment: sandbox
data:
  prometheus.yml: |
    global:
      scrape_interval: "15s"
      scrape_timeout: "10s"
      evaluation_interval: "1m"

    scrape_configs:
      - job_name: http-discovery
        http_sd_configs:
          - url: http://prometheus-http-discovery-service.city-navigator:8000/targets
            refresh_interval: "30s"
            follow_redirects: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server-deployment
  namespace: city-navigator
  labels:
    application: city-navigator
    component: prometheus-server
    environment: sandbox
spec:
  replicas: 1
  template:
    metadata:
      name: prometheus-server
      labels:
        application: city-navigator
        component: prometheus-server
        environment: sandbox
    spec:
      containers:
        - name: prometheus-server
          image: prom/prometheus
          imagePullPolicy: Always
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
              readOnly: true
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
  selector:
    matchLabels:
      application: city-navigator
      component: prometheus-server
      environment: sandbox
  strategy:
    type: RollingUpdate

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-service
  namespace: city-navigator
  labels:
    application: city-navigator
    component: prometheus-server
    environment: sandbox
spec:
  type: ClusterIP
  selector:
    application: city-navigator
    component: prometheus-server
    environment: sandbox
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
