apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: city-navigator
  labels:
    application: city-navigator
    component: redis
    environment: sandbox
spec:
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        application: city-navigator
        component: redis
        environment: sandbox
    spec:
      containers:
        - name: redis
          image: redis:6.2.11-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              protocol: TCP
  selector:
    matchLabels:
      application: city-navigator
      component: redis
      environment: sandbox
  strategy:
    type: RollingUpdate

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: city-navigator
  labels:
    application: city-navigator
    component: redis
    environment: sandbox
spec:
  type: ClusterIP
  selector:
    application: city-navigator
    component: redis
    environment: sandbox
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
