CREATE TABLE T_MEANS_OF_TRANSPORT (
    UUID VARCHAR(36) NOT NULL PRIMARY KEY,
    IDENTIFIER VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE T_STATIONS (
    UUID VARCHAR(36) NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE T_LINES (
    UUID VARCHAR(36) NOT NULL PRIMARY KEY,
    LABEL VARCHAR(5) NOT NULL UNIQUE,
    MEANS_OF_TRANSPORT_UUID VARCHAR(36) NOT NULL,
    TERMINAL_STOP_ONE_UUID VARCHAR(36) NOT NULL,
	TERMINAL_STOP_TWO_UUID VARCHAR(36) NOT NULL,
    CONSTRAINT MEANS_OF_TRANSPORT_FK FOREIGN KEY (MEANS_OF_TRANSPORT_UUID) REFERENCES T_MEANS_OF_TRANSPORT(UUID),
    CHECK (TERMINAL_STOP_ONE_UUID <> TERMINAL_STOP_TWO_UUID),
	CONSTRAINT TERMINAL_STOP_ONE_FK FOREIGN KEY (TERMINAL_STOP_ONE_UUID) REFERENCES T_STATIONS(UUID),
	CONSTRAINT TERMINAL_STOP_TWO_FK FOREIGN KEY (TERMINAL_STOP_TWO_UUID) REFERENCES T_STATIONS(UUID)
);

CREATE TABLE T_EDGES (
    UUID VARCHAR(36) NOT NULL PRIMARY KEY,
    START_STATION_UUID VARCHAR(36) NOT NULL,
    END_STATION_UUID VARCHAR(36) NOT NULL,
    LINE_UUID VARCHAR(36) NOT NULL,
    DISTANCE_MIN INTEGER NOT NULL,
    CONSTRAINT LINE_FK FOREIGN KEY (LINE_UUID) REFERENCES T_LINES(UUID) ON DELETE CASCADE,
    CHECK (DISTANCE_MIN > 0),
    CONSTRAINT START_STATION_FK FOREIGN KEY (START_STATION_UUID) REFERENCES T_STATIONS(UUID),
    CONSTRAINT END_STATION_FK FOREIGN KEY (END_STATION_UUID) REFERENCES T_STATIONS(UUID),
    CHECK (START_STATION_UUID <> END_STATION_UUID),
    CONSTRAINT EDGE_UK UNIQUE(START_STATION_UUID, END_STATION_UUID, LINE_UUID)
);
