global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

scrape_configs:
  - job_name: http-discovery
    http_sd_configs:
      - url: http://prometheus-http-discovery:8000/targets
        refresh_interval: "30s"
        follow_redirects: true
