#
# Copyright 2023 Jaroslav Chmurny
#
# This file is part of City Navigator.
#
# City Navigator is free software developed for educational and experimental
# purposes. It is licensed under the Apache License, Version 2.0 # (the
# "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

services:
  master-data-service:
    image: jardo72/city-navigator-master-data-service:latest
    environment:
      - DATABASE_URL=sqlite:////db/sqlite.db
    networks:
      - service-network
    volumes:
      - type: bind
        source: ./data
        target: /db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  query-service:
    image: jardo72/city-navigator-query-service:latest
    depends_on:
      - master-data-service
    environment:
      - MASTER_DATA_SERVICE_BASE_URL=http://master-data-service:8000
    networks:
      - service-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  http-router:
    image: jardo72/city-navigator-router:latest
    depends_on:
      - master-data-service
      - query-service
    expose:
      - 80
    networks:
      - service-network
    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  service-network:
    driver: bridge
