#
# Copyright 2023 Jaroslav Chmurny
#
# This file is part of City Navigator.
#
# City Navigator is free software developed for educational and experimental
# purposes. It is licensed under the Apache License, Version 2.0 # (the
# "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

services:
  redis-pubsub:
    image: redis:6.2.11-alpine
    expose:
      - 6379
    networks:
      - service-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s

  master-data-service:
    image: jardo72/city-navigator-master-data-service:latest
    depends_on:
      - redis-pubsub
    environment:
      - DATABASE_URL=sqlite:////db/sqlite.db
      - REDIS_HOST=redis-pubsub
      - REDIS_PORT=6379
    expose:
      - 8000
    networks:
      - service-network
    volumes:
      - type: bind
        source: ./data
        target: /db
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 250M
        limits:
          cpus: '0.5'
          memory: 750M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s

  query-service:
    image: jardo72/city-navigator-query-service:latest
    depends_on:
      - redis-pubsub
      - master-data-service
    expose:
      - 8000
    environment:
      - MASTER_DATA_SERVICE_BASE_URL=http://master-data-service:8000
      - REDIS_HOST=redis-pubsub
      - REDIS_PORT=6379
    networks:
      - service-network
    deploy:
      mode: replicated
      replicas: 2
      resources:
        reservations:
          cpus: '0.50'
          memory: 500M
        limits:
          cpus: '1.0'
          memory: 1G
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s

  nginx-http-router:
    image: jardo72/city-navigator-router:latest
    depends_on:
      - master-data-service
      - query-service
    expose:
      - 80
    networks:
      - service-network
    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s

  prometheus-server:
    image: jardo72/city-navigator-prometheus:latest
    depends_on:
      - master-data-server
      - query-service
    networks:
      - service-network
    ports:
      - 9090:9090
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s

networks:
  service-network:
    driver: bridge
