services:
  master-data-service:
    image: jardo72/city-navigator-master-data-service:latest
    environment:
      - DATABASE_URL=sqlite:////db/sqlite.db
    networks:
      - service-network
    volumes:
      - type: bind
        source: ./data
        target: /db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  query-service:
    image: jardo72/city-navigator-query-service:latest
    depends_on:
      - master-data-service
    environment:
      - MASTER_DATA_SERVICE_BASE_URL=http://master-data-service:8000
    networks:
      - service-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  http-router:
    image: jardo72/city-navigator-router:latest
    depends_on:
      - master-data-service
      - query-service
    expose:
      - 80
    networks:
      - service-network
    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  service-network:
    driver: bridge
