#
# Copyright 2026 Jaroslav Chmurny
#
# This file is part of City Navigator.
#
# City Navigator is free software developed for educational and experimental
# purposes. It is licensed under the Apache License, Version 2.0 # (the
# "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-svc-deployment
  namespace: city-navigator
  labels:
    application: city-navigator
    component: query-service
    environment: sandbox
spec:
  replicas: 2
  template:
    metadata:
      name: query-service
      labels:
        application: city-navigator
        component: query-service
        environment: sandbox
    spec:
      containers:
        - name: query-service
          image: jardo72/city-navigator-query-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: API_DOC_ENABLED
              value: "no"
            - name: ROOT_PATH
              value: /city-navigator/api/query
            - name: MASTER_DATA_SERVICE_BASE_URL
              value: http://master-data-svc-service.city-navigator:8000
            - name: REDIS_HOST
              value: redis-service.city-navigator
            - name: REDIS_PORT
              value: "6379"
            - name: WORKER_COUNT
              value: "10"
          resources:
            requests:
              cpu: "1500m"
              memory: "1G"
            limits:
              cpu: "3500m"
              memory: "3G"
          volumeMounts:
            - name: logging-config
              mountPath: /usr/src/app/logging.yaml
              subPath: logging.yaml
      volumes:
        - name: logging-config
          configMap:
            name: query-svc-logging-config
  selector:
    matchLabels:
      application: city-navigator
      component: query-service
      environment: sandbox
  strategy:
    type: RollingUpdate

---
apiVersion: v1
kind: Service
metadata:
  name: query-svc-service
  namespace: city-navigator
  labels:
    application: city-navigator
    component: query-service
    environment: sandbox
spec:
  type: ClusterIP
  selector:
    application: city-navigator
    component: query-service
    environment: sandbox
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
